# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Battery < Formula
  desc "Display your battery status on terminal (or tmux) written by Go"
  homepage "https://github.com/Code-Hex/battery"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Code-Hex/battery/releases/download/v1.0.0/battery_1.0.0_macOS_x86_64.tar.gz"
      sha256 "b6091378f4aa879c7b8bf4e3fd0f8ddde9712ea77bd82e7b28f22c6b6d5d6cde"

      def install
        bin.install "battery"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Code-Hex/battery/releases/download/v1.0.0/battery_1.0.0_macOS_arm64.tar.gz"
      sha256 "3fc324518052b631bb56f997ebc1cce3bfb2778dc711088df1c01fae17b4dd8a"

      def install
        bin.install "battery"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Code-Hex/battery/releases/download/v1.0.0/battery_1.0.0_Linux_x86_64.tar.gz"
      sha256 "1115851dd315a00c6d1a2c1c1a4522c1f7743e19189b3507f9e8b6d7a2e62330"

      def install
        bin.install "battery"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Code-Hex/battery/releases/download/v1.0.0/battery_1.0.0_Linux_arm.tar.gz"
      sha256 "35644fb5a4aeb35a1a02949ecef828b7685ee866eaf4256e0e5c8a31bfc17655"

      def install
        bin.install "battery"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Code-Hex/battery/releases/download/v1.0.0/battery_1.0.0_Linux_arm64.tar.gz"
      sha256 "6744f3e1da1e203b2270df1636823806c243d0d30098263cbf6c4b316ed0a77e"

      def install
        bin.install "battery"
      end
    end
  end
end
