# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gqldoc < Formula
  desc "The easiest way to make documents for GraphQL"
  homepage "https://github.com/Code-Hex/gqldoc"
  version "0.0.3"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/Code-Hex/gqldoc/releases/download/v0.0.3/gqldoc_0.0.3_macOS_x86_64.tar.gz"
    sha256 "f71c36511a892095417448c78b498352ceba00ee57cab5026a8c755d707492fc"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/Code-Hex/gqldoc/releases/download/v0.0.3/gqldoc_0.0.3_macOS_arm64.tar.gz"
    sha256 "6a68fba11d6f9b9430be014ce1a58e09a66fdf74edc61e5c2d3172f3ba0b60dd"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/Code-Hex/gqldoc/releases/download/v0.0.3/gqldoc_0.0.3_Linux_x86_64.tar.gz"
    sha256 "5af812f83cf9d2b51d20c1ecd809a0b27acb2fdaf1f7cdf078591f3fff84294c"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/Code-Hex/gqldoc/releases/download/v0.0.3/gqldoc_0.0.3_Linux_arm.tar.gz"
    sha256 "f36d7c91024d57564e58c78dd17200c6d36b7e5fbb50b53ea5f492705a963861"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/Code-Hex/gqldoc/releases/download/v0.0.3/gqldoc_0.0.3_Linux_arm64.tar.gz"
    sha256 "b92ac1a280ca4676cfd8cfc305cf4dbadf40861fc8816848aa8a467ffa3d3dee"
  end

  def install
    bin.install "gqldoc"
  end
end
