# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gqldoc < Formula
  desc "The easiest way to make documents for GraphQL"
  homepage "https://github.com/Code-Hex/gqldoc"
  version "0.0.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/Code-Hex/gqldoc/releases/download/v0.0.1/gqldoc_0.0.1_macOS_x86_64.tar.gz"
    sha256 "ba6fd40820616986f4dd95bdb3547b85a4d9617c1449eb3640b90592fb592f9d"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/Code-Hex/gqldoc/releases/download/v0.0.1/gqldoc_0.0.1_macOS_arm64.tar.gz"
    sha256 "a713acd9c7526d791d049de2e8e97a7691cc1d424bcb7426de700e7221baeb7c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/Code-Hex/gqldoc/releases/download/v0.0.1/gqldoc_0.0.1_Linux_x86_64.tar.gz"
    sha256 "f3c8c4b1a71a91ef095ae6d1ced28225b85bd95c6ff1c77c6db7aa5943b1747b"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/Code-Hex/gqldoc/releases/download/v0.0.1/gqldoc_0.0.1_Linux_arm.tar.gz"
    sha256 "c0b33ba67b9a116000ea2c0b7e3d6def87107d4d89464b75186979bf1f82a488"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/Code-Hex/gqldoc/releases/download/v0.0.1/gqldoc_0.0.1_Linux_arm64.tar.gz"
    sha256 "11279bffd12da1f1b0cc93c2ffcd1a00edc2f147509077221ed64c93a23bd048"
  end

  def install
    bin.install "gqldoc"
  end
end
