# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NeoCowsay < Formula
  desc "Fast, funny, everyone wanted? new cowsay!!"
  homepage "https://github.com/Code-Hex/Neo-cowsay"
  version "2.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Code-Hex/Neo-cowsay/releases/download/v2.0.1/cowsay_2.0.1_macOS_x86_64.tar.gz"
      sha256 "d9110fda9a1fa3efb0c7c62aa53c908e5faa21ec7c9ceef0d670f96052795f00"

      def install
        bin.install "cowsay"
        bin.install "cowthink"
        man1.install Dir["doc/cowsay.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Code-Hex/Neo-cowsay/releases/download/v2.0.1/cowsay_2.0.1_macOS_arm64.tar.gz"
      sha256 "00ed921bc83eaf92c1e19ce436187b43a8a10c33058b8da11977f6effef3e06a"

      def install
        bin.install "cowsay"
        bin.install "cowthink"
        man1.install Dir["doc/cowsay.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Code-Hex/Neo-cowsay/releases/download/v2.0.1/cowsay_2.0.1_Linux_arm.tar.gz"
      sha256 "27422c6ee27d557b95c5e0b677ac3fab1f7fda8b78bc3b2f038686435cbdc734"

      def install
        bin.install "cowsay"
        bin.install "cowthink"
        man1.install Dir["doc/cowsay.1"]
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Code-Hex/Neo-cowsay/releases/download/v2.0.1/cowsay_2.0.1_Linux_x86_64.tar.gz"
      sha256 "45c34bda3a8c4bcef66903248eadecfdf2ceec992fdc90eab06a9bde35a1b8f8"

      def install
        bin.install "cowsay"
        bin.install "cowthink"
        man1.install Dir["doc/cowsay.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Code-Hex/Neo-cowsay/releases/download/v2.0.1/cowsay_2.0.1_Linux_arm64.tar.gz"
      sha256 "6bc462340cca62ac0859836ba75ba57a49a03bb389e5b675d4b4afc84a6236dc"

      def install
        bin.install "cowsay"
        bin.install "cowthink"
        man1.install Dir["doc/cowsay.1"]
      end
    end
  end
end
