# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NeoCowsay < Formula
  desc "Fast, funny, everyone wanted? new cowsay!!"
  homepage "https://github.com/Code-Hex/Neo-cowsay"
  version "2.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Code-Hex/Neo-cowsay/releases/download/v2.0.3/cowsay_2.0.3_macOS_arm64.tar.gz"
      sha256 "e996fd3ddf00ea9461d1e536c24e18da9044324bed819e32dcb5ccdc78f66294"

      def install
        bin.install "cowsay"
        bin.install "cowthink"
        man1.install Dir["doc/cowsay.1"]
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Code-Hex/Neo-cowsay/releases/download/v2.0.3/cowsay_2.0.3_macOS_x86_64.tar.gz"
      sha256 "447a4a416d68967a13423e4d80895a57ef90313cdfbc391f481f2a60c6224aaa"

      def install
        bin.install "cowsay"
        bin.install "cowthink"
        man1.install Dir["doc/cowsay.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Code-Hex/Neo-cowsay/releases/download/v2.0.3/cowsay_2.0.3_Linux_x86_64.tar.gz"
      sha256 "ebcff2e239dc7035ed9ca031bb35be86bb650ff40d702fbd9f38f9e7712fd1d8"

      def install
        bin.install "cowsay"
        bin.install "cowthink"
        man1.install Dir["doc/cowsay.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Code-Hex/Neo-cowsay/releases/download/v2.0.3/cowsay_2.0.3_Linux_arm64.tar.gz"
      sha256 "8ab01c928f3af8a204048379bc1f9328b4d14d74038b303942cb84dd42fb4b11"

      def install
        bin.install "cowsay"
        bin.install "cowthink"
        man1.install Dir["doc/cowsay.1"]
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Code-Hex/Neo-cowsay/releases/download/v2.0.3/cowsay_2.0.3_Linux_arm.tar.gz"
      sha256 "3f063eaa4ccb570e8c10efe6b432f985cfb9a003f9eb53e85c408913040ceba0"

      def install
        bin.install "cowsay"
        bin.install "cowthink"
        man1.install Dir["doc/cowsay.1"]
      end
    end
  end
end
