# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pget < Formula
  desc "The fastest file download client"
  homepage "https://github.com/Code-Hex/pget"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Code-Hex/pget/releases/download/v0.2.0/pget_ 0.2.0_macOS_arm64.tar.gz"
      sha256 "35ce3b3ac8914a2c219c5ff13124f42d68cc5e6c4c13a8644eee4cfa4289f688"

      def install
        bin.install "pget"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Code-Hex/pget/releases/download/v0.2.0/pget_ 0.2.0_macOS_x86_64.tar.gz"
      sha256 "f32218c5762999c0daf077a7bc27b13cfa2e7770851fef3ed2549b32e1c8f652"

      def install
        bin.install "pget"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Code-Hex/pget/releases/download/v0.2.0/pget_ 0.2.0_Linux_x86_64.tar.gz"
      sha256 "9d05730177c47acec61a39adad9cc0ae0da649d388e1463c95005e31e3ddcecd"

      def install
        bin.install "pget"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Code-Hex/pget/releases/download/v0.2.0/pget_ 0.2.0_Linux_arm64.tar.gz"
      sha256 "a4d971051cf02a0a68dc41296012b710878e711eee3f053a454fc94dce99eb97"

      def install
        bin.install "pget"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Code-Hex/pget/releases/download/v0.2.0/pget_ 0.2.0_Linux_arm.tar.gz"
      sha256 "98ac02efaddda40206e6ae5bb0ed6a4d471712ad3aadf5832e26cac21bd769fa"

      def install
        bin.install "pget"
      end
    end
  end
end
