# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pget < Formula
  desc "The fastest file download client"
  homepage "https://github.com/Code-Hex/pget"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Code-Hex/pget/releases/download/v0.2.1/pget_ 0.2.1_macOS_x86_64.tar.gz"
      sha256 "d524b750efbfd782b77b61b0a16926e34d8593d496d7e5cfeb156325335a9d2b"

      def install
        bin.install "pget"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Code-Hex/pget/releases/download/v0.2.1/pget_ 0.2.1_macOS_arm64.tar.gz"
      sha256 "1a2780c58b0cd5b121d411bca90a8dc637441f64836743af9814ba1bdcc774a7"

      def install
        bin.install "pget"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Code-Hex/pget/releases/download/v0.2.1/pget_ 0.2.1_Linux_x86_64.tar.gz"
      sha256 "a03327eb18616e523686fdc9e997c6be7d4bf313c8313d57316964a63cac3381"

      def install
        bin.install "pget"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Code-Hex/pget/releases/download/v0.2.1/pget_ 0.2.1_Linux_arm.tar.gz"
      sha256 "8a410ad5449833c32a9fb35cfe7859b557496d98d6bb2c2b93321bc25273e527"

      def install
        bin.install "pget"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Code-Hex/pget/releases/download/v0.2.1/pget_ 0.2.1_Linux_arm64.tar.gz"
      sha256 "8d8eb0a84fe5fb9ad1bc6820d73693de3f0582d044e7977db71f5992ff5883c9"

      def install
        bin.install "pget"
      end
    end
  end
end
